#!/usr/bin/env python3
"""Generate Telegraf ping inputs from the known-device inventory."""

from __future__ import annotations

import argparse
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_INVENTORY = REPO_ROOT / "config" / "known_devices.yml"
EXAMPLE_INVENTORY = REPO_ROOT / "config" / "known_devices.example.yml"
DEFAULT_OUTPUT = REPO_ROOT / "telegraf" / "telegraf.conf"


BASE_CONFIG = """[agent]
  interval = "15s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "15s"
  flush_jitter = "0s"
  omit_hostname = false

[[outputs.prometheus_client]]
  listen = ":9273"
  metric_version = 2
"""


def parse_scalar(value: str):
    value = value.strip()
    if value in {"true", "True"}:
        return True
    if value in {"false", "False"}:
        return False
    if (value.startswith('"') and value.endswith('"')) or (
        value.startswith("'") and value.endswith("'")
    ):
        return value[1:-1]
    return value


def parse_devices(path: Path) -> list[dict[str, object]]:
    devices: list[dict[str, object]] = []
    current: dict[str, object] | None = None
    in_devices = False

    for raw_line in path.read_text().splitlines():
        line = raw_line.split("#", 1)[0].rstrip()
        if not line.strip():
            continue
        stripped = line.strip()

        if stripped == "devices:":
            in_devices = True
            continue
        if not in_devices:
            continue

        if stripped.startswith("- "):
            if current:
                devices.append(current)
            current = {}
            remainder = stripped[2:].strip()
            if remainder:
                key, value = parse_key_value(remainder)
                current[key] = value
            continue

        if current is None:
            continue

        key, value = parse_key_value(stripped)
        current[key] = value

    if current:
        devices.append(current)

    return devices


def parse_key_value(line: str) -> tuple[str, object]:
    if ":" not in line:
        raise ValueError(f"Expected key/value line, got: {line}")
    key, value = line.split(":", 1)
    return key.strip(), parse_scalar(value)


def toml_string(value: object) -> str:
    escaped = str(value).replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def should_monitor(device: dict[str, object]) -> bool:
    monitor = str(device.get("monitor", "ping")).lower()
    enabled = device.get("enabled", True)
    return monitor == "ping" and enabled is not False


def render_ping_input(device: dict[str, object]) -> str:
    name = device.get("name")
    ip = device.get("ip")
    role = device.get("role", "device")
    if not name or not ip:
        raise ValueError(f"Known device entries require name and ip: {device}")

    tags = {
        "device_name": name,
        "role": role,
    }
    for optional_tag in ("owner", "criticality", "location"):
        if optional_tag in device and device[optional_tag] not in ("", None):
            tags[optional_tag] = device[optional_tag]

    lines = [
        "[[inputs.ping]]",
        f"  urls = [{toml_string(ip)}]",
        "  count = 3",
        "  ping_interval = 1.0",
        "  timeout = 2.0",
        '  method = "native"',
        "  [inputs.ping.tags]",
    ]
    lines.extend(f"    {key} = {toml_string(value)}" for key, value in tags.items())
    return "\n".join(lines)


def generate(inventory_path: Path, output_path: Path) -> int:
    devices = parse_devices(inventory_path)
    monitored_devices = [device for device in devices if should_monitor(device)]
    if not monitored_devices:
        raise ValueError(f"No ping-monitored devices found in {inventory_path}")

    rendered = [
        BASE_CONFIG.rstrip(),
        "",
        "# Generated by scripts/generate_telegraf_config.py.",
        f"# Source inventory: {inventory_path.relative_to(REPO_ROOT)}",
        "# Edit config/known_devices.yml, then regenerate this file.",
        "",
    ]
    rendered.extend(render_ping_input(device) + "\n" for device in monitored_devices)

    output_path.write_text("\n".join(rendered).rstrip() + "\n")
    return len(monitored_devices)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--inventory",
        type=Path,
        default=DEFAULT_INVENTORY if DEFAULT_INVENTORY.exists() else EXAMPLE_INVENTORY,
        help="Known-device YAML inventory to read.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="Telegraf config path to write.",
    )
    args = parser.parse_args()

    count = generate(args.inventory, args.output)
    print(f"Wrote {count} ping targets to {args.output}")


if __name__ == "__main__":
    main()
